# Copyright © 2020 Interplanetary Database Association e.V.,
# Planetmint and IPDB software contributors.
# SPDX-License-Identifier: (Apache-2.0 AND CC-BY-4.0)
# Code is Apache-2.0 and docs are CC-BY-4.0

---
"$schema": "http://json-schema.org/draft-04/schema#"
type: object
title: Transaction Schema - DECOMPOSE specific constraints
required:
- assets
- inputs
properties:
  assets:
    type: array
    minItems: 1
    items:
      "$ref": "#/definitions/asset"
  inputs:
    type: array
    title: "Transaction inputs"
    maxItems: 1
    items:
      type: "object"
      required:
      - fulfills
      properties:
        fulfills:
            type: "object"
definitions:
  sha3_hexdigest:
    pattern: "[0-9a-f]{64}"
    type: string
  asset:
    oneOf:
      - type: object
        additionalProperties: false
        properties:
          id:
            "$ref": "#/definitions/sha3_hexdigest"
        required:
        - id
      - type: object
        additionalProperties: false
        properties:
          data:
            type: "string"
        required:
        - data
